local M = {}

---@param c table
---@param opts vscode_dark_2026.Config
function M.get(c, opts)
  return {
    Normal = { fg = c.fg, bg = c.bg_normal },
    NormalNC = { fg = c.fg, bg = c.bg_dim },
    NormalFloat = { fg = c.fg_float, bg = c.bg_float },
    NormalSB = { fg = c.fg_sidebar, bg = c.bg_sidebar },
    FloatBorder = { fg = c.border_highlight, bg = c.bg_float },
    FloatTitle = { fg = c.border_highlight, bg = c.bg_float, bold = true },
    FloatFooter = { fg = c.fg_dark, bg = c.bg_float },

    ColorColumn = { bg = c.bg_highlight },
    Conceal = { fg = c.fg_gutter },
    Cursor = { fg = c.bg, bg = c.fg },
    lCursor = { fg = c.bg, bg = c.fg },
    CursorIM = { fg = c.bg, bg = c.fg },
    CursorColumn = { bg = c.bg_highlight },
    CursorLine = { bg = c.bg_highlight },
    CursorLineNr = { fg = c.orange, bold = true },
    LineNr = { fg = c.fg_gutter },
    LineNrAbove = { fg = c.fg_gutter },
    LineNrBelow = { fg = c.fg_gutter },
    SignColumn = { fg = c.fg_gutter, bg = c.bg_normal },
    FoldColumn = { fg = c.fg_gutter, bg = c.bg_normal },
    Folded = { fg = c.fg_dark, bg = c.bg_widget, italic = true },

    WinSeparator = { fg = c.border },
    VertSplit = { fg = c.border },
    WinBar = { fg = c.fg_sidebar, bg = c.bg_statusline },
    WinBarNC = { fg = c.fg_gutter, bg = c.bg_statusline },
    StatusLine = { fg = c.fg_sidebar, bg = c.bg_statusline },
    StatusLineNC = { fg = c.fg_gutter, bg = c.bg_statusline },
    StatusLineTerm = "StatusLine",
    StatusLineTermNC = "StatusLineNC",
    TabLine = { fg = c.fg_dark, bg = c.bg_statusline },
    TabLineSel = { fg = c.fg, bg = c.bg, bold = true },
    TabLineFill = { bg = c.bg_statusline },

    Visual = { bg = c.bg_visual },
    VisualNOS = { bg = c.bg_visual },
    Search = { fg = c.fg, bg = c.bg_search },
    CurSearch = { fg = c.bg, bg = c.orange, bold = true },
    IncSearch = { fg = c.bg, bg = c.orange, bold = true },
    Substitute = { fg = c.bg, bg = c.red1 },
    MatchParen = { fg = c.gold, bg = c.bg_widget, bold = true },
    QuickFixLine = { bg = c.bg_visual, bold = true },

    Pmenu = { fg = c.fg, bg = c.bg_popup },
    PmenuSel = { fg = c.fg, bg = c.bg_visual, bold = true },
    PmenuSbar = { bg = c.bg_widget },
    PmenuThumb = { bg = c.fg_gutter },
    PmenuMatch = { fg = c.blue2, bg = c.bg_popup },
    PmenuMatchSel = { fg = c.blue2, bg = c.bg_visual, bold = true },
    WildMenu = { fg = c.fg, bg = c.bg_visual },

    Directory = { fg = c.teal },
    EndOfBuffer = { fg = opts.transparent and c.none or c.bg },
    NonText = { fg = c.fg_gutter },
    SpecialKey = { fg = c.fg_gutter },
    Whitespace = { fg = c.fg_gutter },
    Title = { fg = c.magenta, bold = true },
    Question = { fg = c.info },
    MoreMsg = { fg = c.git.add },
    ModeMsg = { fg = c.fg, bold = true },
    MsgArea = { fg = c.fg_dark },
    ErrorMsg = { fg = c.error, bold = true },
    WarningMsg = { fg = c.warning },

    SpellBad = { sp = c.error, undercurl = true },
    SpellCap = { sp = c.warning, undercurl = true },
    SpellLocal = { sp = c.info, undercurl = true },
    SpellRare = { sp = c.hint, undercurl = true },

    DiffAdd = { bg = c.diff.add },
    DiffChange = { bg = c.diff.change },
    DiffDelete = { bg = c.diff.delete },
    DiffText = { bg = c.diff.text },
    Added = { fg = c.git.add },
    Changed = { fg = c.git.change },
    Removed = { fg = c.git.delete },

    Comment = { fg = c.comment, style = opts.styles.comments },
    Constant = { fg = c.blue1 },
    String = { fg = c.cyan },
    Character = { fg = c.cyan },
    Number = { fg = c.green },
    Boolean = { fg = c.blue },
    Float = { fg = c.green },
    Identifier = { fg = c.fg, style = opts.styles.variables },
    Function = { fg = c.magenta, style = opts.styles.functions },
    Statement = { fg = c.red },
    Conditional = { fg = c.purple },
    Repeat = { fg = c.purple },
    Label = { fg = c.red },
    Operator = { fg = c.fg },
    Keyword = { fg = c.red, style = opts.styles.keywords },
    Exception = { fg = c.purple },
    PreProc = { fg = c.red },
    Include = { fg = c.red },
    Define = { fg = c.red },
    Macro = { fg = c.blue },
    PreCondit = { fg = c.red },
    Type = { fg = c.teal },
    StorageClass = { fg = c.red },
    Structure = { fg = c.teal },
    Typedef = { fg = c.teal },
    Special = { fg = c.magenta },
    SpecialChar = { fg = c.cyan },
    Tag = { fg = c.blue1 },
    Delimiter = { fg = c.fg },
    SpecialComment = { fg = c.comment, bold = true },
    Debug = { fg = c.warning },
    Underlined = { fg = c.info, underline = true },
    Bold = { bold = true },
    Italic = { italic = true },
    Error = { fg = c.error },
    Todo = { fg = c.blue, bg = c.bg_widget, bold = true },
    Ignore = { fg = c.fg_gutter },

    DiagnosticError = { fg = c.error },
    DiagnosticWarn = { fg = c.warning },
    DiagnosticInfo = { fg = c.info },
    DiagnosticHint = { fg = c.hint },
    DiagnosticOk = { fg = c.git.add },
    DiagnosticSignError = { fg = c.error },
    DiagnosticSignWarn = { fg = c.warning },
    DiagnosticSignInfo = { fg = c.info },
    DiagnosticSignHint = { fg = c.hint },
    DiagnosticSignOk = { fg = c.git.add },
    DiagnosticUnderlineError = { sp = c.error, undercurl = true },
    DiagnosticUnderlineWarn = { sp = c.warning, undercurl = true },
    DiagnosticUnderlineInfo = { sp = c.info, undercurl = true },
    DiagnosticUnderlineHint = { sp = c.hint, undercurl = true },
    DiagnosticUnderlineOk = { sp = c.git.add, undercurl = true },
    DiagnosticVirtualTextError = { fg = c.error, bg = c.virtual_text.error },
    DiagnosticVirtualTextWarn = { fg = c.warning, bg = c.virtual_text.warning },
    DiagnosticVirtualTextInfo = { fg = c.info, bg = c.virtual_text.info },
    DiagnosticVirtualTextHint = { fg = c.hint, bg = c.virtual_text.hint },
    DiagnosticVirtualTextOk = { fg = c.git.add, bg = c.diff.add },
    DiagnosticFloatingError = { fg = c.error },
    DiagnosticFloatingWarn = { fg = c.warning },
    DiagnosticFloatingInfo = { fg = c.info },
    DiagnosticFloatingHint = { fg = c.hint },
    DiagnosticFloatingOk = { fg = c.git.add },

    LspReferenceText = { bg = c.bg_widget },
    LspReferenceRead = { bg = c.bg_widget },
    LspReferenceWrite = { bg = c.bg_widget },
    LspSignatureActiveParameter = { fg = c.orange, bg = c.bg_visual, bold = true },
    LspCodeLens = { fg = c.comment },
    LspCodeLensSeparator = { fg = c.fg_gutter },
    LspInlayHint = { fg = c.fg_dark, bg = c.bg_highlight },
    LspInfoBorder = "FloatBorder",

    debugBreakpoint = { fg = c.info, bg = c.virtual_text.info },
    debugPC = { bg = c.bg_sidebar },
    qfFileName = { fg = c.blue2 },
    qfLineNr = { fg = c.fg_gutter },
    htmlH1 = { fg = c.red, bold = true },
    htmlH2 = { fg = c.magenta, bold = true },
  }
end

return M
