local M = {}

---@param c table
---@param opts vscode_dark_2026.Config
function M.get(c, opts)
  return {
    ["@variable"] = { fg = c.fg, style = opts.styles.variables },
    ["@variable.builtin"] = { fg = c.red },
    ["@variable.parameter"] = { fg = c.orange },
    ["@variable.parameter.builtin"] = { fg = c.red },
    ["@variable.member"] = { fg = c.fg },
    ["@constant"] = { fg = c.blue1 },
    ["@constant.builtin"] = { fg = c.blue },
    ["@constant.macro"] = { fg = c.blue },
    ["@module"] = { fg = c.teal },
    ["@module.builtin"] = { fg = c.teal },
    ["@namespace"] = "@module",
    ["@label"] = { fg = c.blue1 },

    ["@string"] = { fg = c.cyan },
    ["@string.documentation"] = { fg = c.comment, italic = true },
    ["@string.regexp"] = { fg = c.cyan },
    ["@string.escape"] = { fg = c.red },
    ["@string.special"] = { fg = c.cyan },
    ["@string.special.url"] = { fg = c.info, underline = true },
    ["@string.special.symbol"] = { fg = c.blue1 },
    ["@character"] = { fg = c.cyan },
    ["@character.special"] = { fg = c.red },
    ["@number"] = { fg = c.green },
    ["@number.float"] = { fg = c.green },
    ["@boolean"] = { fg = c.blue },

    ["@type"] = { fg = c.teal },
    ["@type.builtin"] = { fg = c.teal },
    ["@type.definition"] = { fg = c.teal },
    ["@attribute"] = { fg = c.red },
    ["@attribute.builtin"] = { fg = c.red },
    ["@property"] = { fg = c.fg },

    ["@function"] = { fg = c.magenta, style = opts.styles.functions },
    ["@function.builtin"] = { fg = c.yellow },
    ["@function.call"] = { fg = c.magenta, style = opts.styles.functions },
    ["@function.macro"] = { fg = c.blue },
    ["@function.method"] = { fg = c.magenta, style = opts.styles.functions },
    ["@function.method.call"] = { fg = c.magenta, style = opts.styles.functions },
    ["@method"] = "@function.method",
    ["@method.call"] = "@function.method.call",
    ["@constructor"] = { fg = c.teal },
    ["@operator"] = { fg = c.fg },

    ["@keyword"] = { fg = c.red, style = opts.styles.keywords },
    ["@keyword.coroutine"] = { fg = c.red, style = opts.styles.keywords },
    ["@keyword.function"] = { fg = c.red, style = opts.styles.keywords },
    ["@keyword.operator"] = { fg = c.red, style = opts.styles.keywords },
    ["@keyword.import"] = { fg = c.red, style = opts.styles.keywords },
    ["@keyword.type"] = { fg = c.red, style = opts.styles.keywords },
    ["@keyword.modifier"] = { fg = c.red, style = opts.styles.keywords },
    ["@keyword.repeat"] = { fg = c.purple, style = opts.styles.keywords },
    ["@keyword.return"] = { fg = c.purple, style = opts.styles.keywords },
    ["@keyword.debug"] = { fg = c.warning },
    ["@keyword.exception"] = { fg = c.purple, style = opts.styles.keywords },
    ["@keyword.conditional"] = { fg = c.purple, style = opts.styles.keywords },
    ["@keyword.conditional.ternary"] = { fg = c.purple, style = opts.styles.keywords },
    ["@keyword.directive"] = { fg = c.red },
    ["@keyword.directive.define"] = { fg = c.red },

    ["@punctuation.delimiter"] = { fg = c.fg },
    ["@punctuation.bracket"] = { fg = c.fg },
    ["@punctuation.special"] = { fg = c.fg },
    ["@comment"] = { fg = c.comment, style = opts.styles.comments },
    ["@comment.documentation"] = { fg = c.comment, italic = true },
    ["@comment.error"] = { fg = c.error, bold = true },
    ["@comment.warning"] = { fg = c.warning, bold = true },
    ["@comment.todo"] = { fg = c.blue, bold = true },
    ["@comment.note"] = { fg = c.info, bold = true },

    ["@markup.strong"] = { bold = true },
    ["@markup.italic"] = { italic = true },
    ["@markup.strikethrough"] = { strikethrough = true },
    ["@markup.underline"] = { underline = true },
    ["@markup.heading"] = { fg = c.magenta, bold = true },
    ["@markup.heading.1"] = { fg = c.red, bold = true },
    ["@markup.heading.2"] = { fg = c.magenta, bold = true },
    ["@markup.heading.3"] = { fg = c.teal, bold = true },
    ["@markup.heading.4"] = { fg = c.blue1, bold = true },
    ["@markup.heading.5"] = { fg = c.blue, bold = true },
    ["@markup.heading.6"] = { fg = c.yellow, bold = true },
    ["@markup.quote"] = { fg = c.comment, italic = true },
    ["@markup.math"] = { fg = c.green },
    ["@markup.link"] = { fg = c.info },
    ["@markup.link.label"] = { fg = c.magenta },
    ["@markup.link.url"] = { fg = c.info, underline = true },
    ["@markup.raw"] = { fg = c.cyan },
    ["@markup.raw.block"] = { fg = c.cyan },
    ["@markup.list"] = { fg = c.red },
    ["@markup.list.checked"] = { fg = c.git.add },
    ["@markup.list.unchecked"] = { fg = c.fg_dark },

    ["@diff.plus"] = { fg = c.git.add },
    ["@diff.minus"] = { fg = c.git.delete },
    ["@diff.delta"] = { fg = c.git.change },
    ["@tag"] = { fg = c.red },
    ["@tag.builtin"] = { fg = c.red },
    ["@tag.attribute"] = { fg = c.orange },
    ["@tag.delimiter"] = { fg = c.fg },

    ["@text"] = { fg = c.fg },
    ["@text.strong"] = "@markup.strong",
    ["@text.emphasis"] = "@markup.italic",
    ["@text.underline"] = "@markup.underline",
    ["@text.strike"] = "@markup.strikethrough",
    ["@text.title"] = "@markup.heading",
    ["@text.literal"] = "@markup.raw",
    ["@text.uri"] = "@markup.link.url",
    ["@text.todo"] = "@comment.todo",
    ["@text.note"] = "@comment.note",
    ["@text.warning"] = "@comment.warning",
    ["@text.danger"] = "@comment.error",
  }
end

return M
